# syntax=docker/dockerfile:1.3
ARG VERSION_ARG
ARG NODE_VERSION_ARG
ARG COMPOSER_VERSION_ARG

FROM composer:${COMPOSER_VERSION_ARG:-2.5.8} AS composer
FROM node:${NODE_VERSION_ARG:-18}-alpine3.18 AS node
FROM php:${VERSION_ARG:-8.2.15}-fpm-alpine3.18 AS fpm-prd

# include(fpm-prd.m4)

FROM fpm-prd AS fpm-dev

# include(fpm-dev.m4)

FROM fpm-prd AS apache-prd

# include(apache.m4)

FROM fpm-dev AS apache-dev

# include(apache.m4)

FROM fpm-prd AS nginx-prd

# include(nginx.m4)

FROM fpm-dev AS nginx-dev

# include(nginx.m4)

FROM php:${VERSION_ARG:-8.2.15}-cli-alpine3.18 AS cli-prd

# include(cli-prd.m4)

FROM cli-prd AS cli-dev

# include(cli-dev.m4)